openapi: 3.0.0

info:
  title: Example app
  version: "0.0.0"
paths:
  /healthz/live:
    get:
      operationId: app.healthz_live
      summary: Liveness check
      tags:
        - healthcheck
      responses:
        "200": {description: Success}
        "500": {description: Failure}
  /get-data:
    get:
      operationId: app.get_data
      summary: Fetch all the data
      tags:
        - getdata
      parameters:
        - name: key
          in: query
          required: true
          schema:
            type: string
      responses:
        "200": {description: Success}
        "500": {description: Failure}
components:
  schemas: {}
